version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ignite
      POSTGRES_PASSWORD: ignite
      POSTGRES_DB: unity_school_datawarehouse
    ports:
      - "5434:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./data_assets/csv_files:/data 
      - ./ingestion/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge